/** Exemples affichés sur la page d'accueil (aucune donnée réelle). */

export const DEMO_CARDS = [
  {
    id: 'demo-standard',
    slug: 'awa-traore',
    template: 'standard',
    theme: { primary: '#0f766e', accent: '#facc15', font: 'sans' },
    profile: {
      firstName: 'Awa',
      lastName: 'Traoré',
      profession: 'Consultante en marketing digital',
      phone: '+225 07 00 12 34 56',
      whatsapp: '+225 07 00 12 34 56',
      email: 'awa@studio-akwaba.ci',
      city: 'Abidjan',
      country: "Côte d'Ivoire",
    },
    companies: [{ id: 'c1', name: 'Studio Akwaba' }],
    socials: [
      { key: 'instagram', value: 'instagram.com/studioakwaba', enabled: true },
      { key: 'linkedin', value: 'linkedin.com/in/awatraore', enabled: true },
      { key: 'website', value: 'studio-akwaba.ci', enabled: true },
    ],
    about: "Consultante indépendante, j'accompagne les petites entreprises dans leur passage au digital.",
    activities: ['Marketing digital', 'Community management', 'Formation'],
  },
  {
    id: 'demo-premium',
    slug: 'jean-dupont',
    template: 'premium',
    theme: { primary: '#5b21b6', accent: '#f5b229', font: 'display' },
    profile: {
      firstName: 'Jean',
      lastName: 'Dupont',
      profession: 'Architecte d’intérieur',
      phone: '+33 6 12 34 56 78',
      whatsapp: '+33 6 12 34 56 78',
      email: 'contact@jeandupont.fr',
      city: 'Lyon',
      country: 'France',
    },
    companies: [{ id: 'c1', name: 'Atelier Dupont' }],
    socials: [
      { key: 'instagram', value: 'instagram.com/atelierdupont', enabled: true },
      { key: 'linkedin', value: 'linkedin.com/in/jeandupont', enabled: true },
      { key: 'youtube', value: 'youtube.com/@atelierdupont', enabled: true },
      { key: 'website', value: 'jeandupont.fr', enabled: true },
    ],
    about: "Architecte d'intérieur, je conçois des espaces qui racontent une histoire.",
    activities: ['Architecture intérieure', 'Décoration', 'Suivi de chantier'],
  },
  {
    id: 'demo-vip',
    slug: 'chantal-mbeki',
    template: 'vip',
    theme: { primary: '#141728', accent: '#f5b229', font: 'serif' },
    profile: {
      firstName: 'Chantal',
      lastName: 'Mbeki',
      profession: 'Avocate d’affaires',
      phone: '+237 6 99 88 77 66',
      whatsapp: '+237 6 99 88 77 66',
      email: 'c.mbeki@cabinet-mbeki.cm',
      city: 'Douala',
      country: 'Cameroun',
    },
    companies: [{ id: 'c1', name: 'Cabinet Mbeki & Associés' }],
    socials: [
      { key: 'linkedin', value: 'linkedin.com/in/chantalmbeki', enabled: true },
      { key: 'website', value: 'cabinet-mbeki.cm', enabled: true },
    ],
    about: "Cabinet spécialisé en droit des affaires et accompagnement des entreprises.",
    activities: ['Droit des affaires', 'Contrats', 'Contentieux'],
  },
]
